### ISSUE TITLE
`ob run` does not work with own Prelude

### ISSUE THREAD

**Issue by maralorn** [obsidiansystems/obelisk#725]
#### To Reproduce

1. ob init
2. Create `common/src/Prelude.hs` add it to `common.cabal`
3. run `ob run`.

#### Error

```
Loading ghci -ignore-dot-ghci -no-user-package-db -package-env - -F -pgmF /nix/store/gd99xxp41i5dllhpx341rxscgbyzlpqn-obelisk-command-0.8.0.0/bin/.ob-wrapped -optF __preprocessor-apply-packages -optF backend/backend.cabal -optF common/common.cabal -optF frontend/frontend.cabal -ibackend/src:common/src:frontend/src -ghci-script /tmp/ob-ghci-f5ba8bc8df8585b5/.ghci ...
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help

<interactive>:1:1: error:
    attempting to use module ‘main:Prelude’ (common/src/Prelude.hs) which is not loaded
Command "ghci -ignore-dot-ghci -no-user-package-db -package-env - -F -pgmF /nix/store/gd99xxp41i5dllhpx341rxscgbyzlpqn-obelisk-command-0.8.0.0/bin/.ob-wrapped -optF __preprocessor-apply-packages -optF backend/backend.cabal -optF common/common.cabal -optF frontend/frontend.cabal -ibackend/src:common/src:frontend/src -ghci-script /tmp/ob-ghci-f5ba8bc8df8585b5/.ghci" exited unexpectedly with error message:     attempting to use module ‘main:Prelude’ (common/src/Prelude.hs) which is not loaded
```

This has something to do with a special handling of the name `Prelude` and is a regression. I didn‘t have the problem before bumping to master today.

**Comment by 3noch** [comment]
Is the module literally called `Prelude`?

**Comment by maralorn** [comment]
Yes. It works like this: include `base-noprelude` instead of `base` in the cabal file. Then in `Prelude.hs` I define my own `Prelude`, e.g. importing `Relude`. It‘s a recommended practice to have your own project specific `Prelude`. The magic is that ghc (or cabal?) will always implicitly include `Prelude` even if it is not from base.

See https://hackage.haskell.org/package/relude-0.6.0.0/relude-0.6.0.0/src#base-noprelude

**Comment by alexfmpe** [comment]
> It‘s a recommended practice to have your own project specific Prelude

It is?

**Comment by maralorn** [comment]
> > It‘s a recommended practice to have your own project specific Prelude
> 
> It is?

Well. It is recommended by someone. The documentation I linked above says:

> This is the recommended way to use custom prelude. 

So I am correct in a literal sense.^^ If you think there is a better way for me to do it, I can just switch and we ignore this issue …

**Comment by alexfmpe** [comment]
To me, "Recommended way to use custom prelude" reads as "if you're using a custom prelude, it is recommended to do it this way", not as "using a custom prelude is recommended"

**Comment by maralorn** [comment]
Oh, no. Sorry. Now I understand. 

It‘s the recommended way to have a custom Prelude if you want to have custom Prelude.
I didn‘t mean to say that it‘s recommend to have a custom Prelude.^^

**Comment by alexfmpe** [comment]
Ah I see, you original sentence worked both ways and I interpreted it in the way you didn't mean.

**Comment by maralorn** [comment]
My ob run broke on this commit. https://github.com/maralorn/kassandra/commit/ae9990fc61c693cb0036eb3c1704abf97f72dacf

**Comment by maralorn** [comment]
I have tried working around this by renaming my `Prelude` and importing it manually. 

But now I encounter the problem, that `ob run` seems to be importing the `base` `Prelude` even though I have hidden it via mixins _and_ by setting the `NoImplicitPrelude` extension.

So my modules 1. are not importing `Prelude` and 2. could not import `Prelude` since `cabal` shouldn‘t expose it to them but still in `ob run` I get name collisions for e.g. `elem` because of `elem` from the `base` `Prelude`.

**Comment by maralorn** [comment]
This also affects `ob profile`, pasting it here because the error looks different:
```
building '/nix/store/2pb5m75z2flsfqsxxf77llcbylra5bmp-ob-run.drv'...
[1 of 1] Compiling Main             ( ob-run.hs, ob-run.o )

ob-run.hs:1:8: error:
    Ambiguous module name `Prelude':
      it was found in multiple packages: base-4.12.0.0 common-0.1
  |
1 | module Main where
  |        ^^^^
```

**Comment by 3noch** [comment]
Very interesting. I would have expected the issue to be in the preprocessor for ob run, but apparently not.

**Comment by maralorn** [comment]
I am sorry. I just realized that the issue didn‘t first pop up in the latest obelisk bump but a bit before, i.e. it broke in https://github.com/maralorn/kassandra/commit/9e5980a9b51ca5d87a6c15280c2478b1c4ba071b.

**Comment by 3noch** [comment]
Thank you. That might help narrow down.

**Comment by maralorn** [comment]
I did a quick bisect.
```
❯ git bisect bad
52660352b19e36d06ebd12b3d1c5e8e7787e57c9 is the first bad commit
commit 52660352b19e36d06ebd12b3d1c5e8e7787e57c9
Author: 3noch <eacameron@gmail.com>
Date:   Sat Apr 18 21:09:04 2020 -0400

    command: Put all ghci configurations in the same place

 lib/command/src/Obelisk/Command/Project.hs | 16 ++++--
 lib/command/src/Obelisk/Command/Run.hs     | 82 ++++++++++++++++--------------
 2 files changed, 56 insertions(+), 42 deletions(-)
```

**Comment by 3noch** [comment]
Ah interesting. In that commit I switched from using `:set` to load all the paths to passing them on the command-line. I don't know exactly how that would impact this but it's at least mildly plausible.

**Comment by maralorn** [comment]
#735 fixed it for me. Thank you so much!
